# Generated by Django 5.2.18 on 2026-10-08 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('Documentid', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'huéspedes',
                'db_table': 'huespeddes',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CHECKIN', 'En casa'), ('CHECKOUT', 'Fuera de casa'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='rooms.habitacion')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='frontdesk.huesped')),
            ],
            options={
                'db_table': 'reservas',
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_salida__gt', models.F('fecha_entrada'))), name='reserva_salida_despues_de_entrada')],
            },
        ),
    ]
