# Generated by Django 5.2.18 on 2026-10-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huesped',
            old_name='Documentid',
            new_name='Documento_identidad',
        ),
        migrations.RenameField(
            model_name='huesped',
            old_name='nombre',
            new_name='nombre_completo',
        ),
    ]
