# frontend/nginx.conf
server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Redirige todas las peticiones al index.html para que el enrutador de React/Vue maneje las rutas
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Cachear archivos estáticos
    location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}