# Generated by Django 5.2.18 on 2026-10-08 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontdesk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'turnos_caja',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CARGO', 'Cargo'), ('PAGO', 'Pago')], max_length=5)),
                ('metodo', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='frontdesk.reserva')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='cashier.turnocaja')),
            ],
            options={
                'db_table': 'transacciones',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='turnocaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTO')), fields=('usuario',), name='un_turno_abierto_por_usuario'),
        ),
    ]
